DROP SEQUENCE IF EXISTS CORRELATION_ID_SEQ;
DROP TABLE IF EXISTS TESTCASE_HISTORY;
DROP TABLE IF EXISTS INVOKE_RECORD;

CREATE SEQUENCE CORRELATION_ID_SEQ;
DROP TABLE IF EXISTS TESTCASE_HISTORY;
CREATE
  TABLE TESTCASE_HISTORY
  (
    ID BIGINT AUTO_INCREMENT,
	CORRELATION_ID 		VARCHAR(20),
    CLIENTREFUNDID      VARCHAR(50),
    CREDITREASON        VARCHAR(255),
    NETWORKSTATUS       VARCHAR(10),
    CLIENTTRANSACTIONID VARCHAR(50),
    PURCHASECURRENCY    VARCHAR(10),
    UID              VARCHAR(50),
    CREDITDATE          TIMESTAMP,
    REQUESTID           VARCHAR(50),
    REVERSEDATE         TIMESTAMP,
    REFUNDCURRENCY      VARCHAR(10),
    MSISDN              VARCHAR(20),
    PRODUCTDESCRIPTION  VARCHAR(255),
    REFUNDAMOUNT LONG,
    ORDERNO   VARCHAR(20),
    API_RADIO VARCHAR(50),
    REFUNDREASON VARCHAR(255),
    PAYMENTREQUESTID VARCHAR(50),
    CLIENTCREDITID   VARCHAR(50),
    MESSAGE          VARCHAR(50),
    REFUNDREQUESTID  VARCHAR(50),
    ISSUERPAYMENTID  VARCHAR(50),
    ISSUERREVERSEID  VARCHAR(50),
    ISSUERREFUNDID  VARCHAR(50),
    ISSUERCREDITID  VARCHAR(50),
    PURCHASEAMOUNT LONG,
    CHARGEREQUESTID VARCHAR(50),
    CREDITCURRENCY VARCHAR(10),
    CREDITAMOUNT LONG,
    CHARGEDATE   TIMESTAMP,
    REFUNDDATE   TIMESTAMP,
    ACCOUNT VARCHAR(50),
	CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );
  
CREATE TABLE INVOKE_RECORD
  (
    CORRELATION_ID VARCHAR(20),
    SEND_MESSAGE CLOB,
    RECEIVE_MESSAGE CLOB,
    RESULT        VARCHAR(25),
    USER_MESSAGE  VARCHAR(255),
    SOAP_CALL     VARCHAR(50),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );